#!/usr/bin/env -S awk -f

# This just generates a package comment from the README

{
    print "// " $0
}

END {
    print "package sqlh\n"
    print "// Code generated by ./readme.awk: DO NOT EDIT."
}